package domain

import "errors"

// Domain errors
var (
	// Erros gerais
	ErrTenantIDRequired = errors.New("tenant_id é obrigatório")
	ErrUnitIDRequired   = errors.New("unit_id é obrigatório")
	ErrInvalidID        = errors.New("ID inválido")
	ErrInvalidTenantID  = errors.New("tenant_id inválido")
	ErrNotFound         = errors.New("recurso não encontrado")
	ErrAlreadyExists    = errors.New("recurso já existe")

	// Erros de MesAno
	ErrMesAnoRequired = errors.New("mes_ano é obrigatório")
	ErrMesAnoInvalido = errors.New("mes_ano inválido (formato esperado: YYYY-MM)")

	// Erros de valores monetários
	ErrValorInvalido = errors.New("valor inválido")
	ErrValorNegativo = errors.New("valor não pode ser negativo")
	ErrValorZero     = errors.New("valor não pode ser zero")

	// Erros de status
	ErrStatusInvalido = errors.New("status inválido")

	// Erros de compensação
	ErrCompensacaoJaCompensada = errors.New("compensação já está marcada como compensada")
	ErrDataCompensacaoInvalida = errors.New("data de compensação inválida")

	// Erros de contas
	ErrContaJaPaga            = errors.New("conta já está paga")
	ErrContaCancelada         = errors.New("conta está cancelada")
	ErrDataVencimentoInvalida = errors.New("data de vencimento inválida")

	// Erros de metas
	ErrMetaInvalida = errors.New("meta inválida")
	ErrMetaNegativa = errors.New("meta não pode ser negativa")

	// Erros de precificação
	ErrMargemInvalida = errors.New("margem inválida (deve estar entre 5-100%)")
	ErrMarkupInvalido = errors.New("markup inválido (deve ser >= 1)")

	// Erros de autenticação
	ErrEmailNaoEncontrado   = errors.New("Email não encontrado")
	ErrSenhaIncorreta       = errors.New("Senha incorreta")
	ErrContaDesativada      = errors.New("Conta desativada")
	ErrRefreshTokenInvalido = errors.New("Refresh token inválido ou expirado")
	ErrUsuarioNaoEncontrado = errors.New("Usuário não encontrado")
	ErrTokenInvalido        = errors.New("Token inválido")

	// Erros de agendamento
	ErrAppointmentProfessionalRequired    = errors.New("profissional é obrigatório")
	ErrAppointmentCustomerRequired        = errors.New("cliente é obrigatório")
	ErrAppointmentStartTimeRequired       = errors.New("horário de início é obrigatório")
	ErrAppointmentServicesRequired        = errors.New("pelo menos um serviço é obrigatório")
	ErrAppointmentInvalidStatus           = errors.New("status de agendamento inválido")
	ErrAppointmentInvalidStatusTransition = errors.New("transição de status inválida")
	ErrAppointmentInvalidTimeRange        = errors.New("intervalo de horário inválido")
	ErrAppointmentConflict                = errors.New("conflito de horário com outro agendamento")
	ErrAppointmentBlockedTimeConflict     = errors.New("conflito: horário bloqueado pelo profissional")
	ErrAppointmentMinimumInterval         = errors.New("intervalo mínimo de 10 minutos entre agendamentos")
	ErrAppointmentCannotReschedule        = errors.New("não é possível reagendar este agendamento")
	ErrAppointmentNotFound                = errors.New("agendamento não encontrado")
	ErrAppointmentProfessionalNotFound    = errors.New("profissional não encontrado")
	ErrAppointmentCustomerNotFound        = errors.New("cliente não encontrado")
	ErrAppointmentServiceNotFound         = errors.New("serviço não encontrado")

	// Erros de cliente
	ErrCustomerNameRequired        = errors.New("nome do cliente é obrigatório")
	ErrCustomerNameTooShort        = errors.New("nome do cliente deve ter pelo menos 3 caracteres")
	ErrCustomerPhoneRequired       = errors.New("telefone do cliente é obrigatório")
	ErrCustomerPhoneInvalid        = errors.New("telefone inválido (deve ter 10 ou 11 dígitos)")
	ErrCustomerPhoneDuplicate      = errors.New("telefone já cadastrado para outro cliente")
	ErrCustomerEmailInvalid        = errors.New("email inválido")
	ErrCustomerEmailDuplicate      = errors.New("email já cadastrado para outro cliente")
	ErrCustomerCPFInvalid          = errors.New("CPF inválido (deve ter 11 dígitos)")
	ErrCustomerCPFDuplicate        = errors.New("CPF já cadastrado para outro cliente")
	ErrCustomerCEPInvalid          = errors.New("CEP inválido (deve ter 8 dígitos)")
	ErrCustomerStateInvalid        = errors.New("UF inválido (deve ter 2 caracteres)")
	ErrCustomerBirthDateFuture     = errors.New("data de nascimento não pode ser futura")
	ErrCustomerDateInvalid         = errors.New("formato de data inválido (esperado: YYYY-MM-DD)")
	ErrCustomerGenderInvalid       = errors.New("gênero inválido (M, F, NB ou PNI)")
	ErrCustomerObservationsTooLong = errors.New("observações devem ter no máximo 500 caracteres")
	ErrCustomerMaxTagsExceeded     = errors.New("máximo de 10 tags por cliente")
	ErrCustomerTagTooLong          = errors.New("tag deve ter no máximo 50 caracteres")
	ErrCustomerNotFound            = errors.New("cliente não encontrado")
	ErrCustomerInactive            = errors.New("cliente está inativo")

	// Erros de Lista da Vez (Barber Turn)
	ErrBarberTurnProfessionalRequired  = errors.New("professional_id é obrigatório")
	ErrBarberTurnProfessionalNotBarber = errors.New("apenas profissionais do tipo BARBEIRO podem ser adicionados à lista da vez")
	ErrBarberTurnProfessionalNotActive = errors.New("profissional deve estar ativo para participar da lista da vez")
	ErrBarberTurnProfessionalNotFound  = errors.New("profissional não encontrado na lista da vez")
	ErrBarberTurnAlreadyInList         = errors.New("profissional já está na lista da vez")
	ErrBarberTurnNotFound              = errors.New("registro não encontrado na lista da vez")
	ErrBarberTurnInvalidPoints         = errors.New("pontuação inválida (não pode ser negativa)")
	ErrBarberTurnCannotRecord          = errors.New("não é possível registrar atendimento para barbeiro pausado")
	ErrBarberTurnMonthYearInvalid      = errors.New("formato de mês/ano inválido (esperado: YYYY-MM)")
	ErrBarberTurnHistoryNotFound       = errors.New("histórico não encontrado para o período especificado")

	// Erros de Categoria de Serviço
	ErrCategoriaNomeRequired     = errors.New("nome da categoria é obrigatório")
	ErrCategoriaNomeTooShort     = errors.New("nome da categoria deve ter pelo menos 2 caracteres")
	ErrCategoriaNomeTooLong      = errors.New("nome da categoria deve ter no máximo 100 caracteres")
	ErrCategoriaNomeDuplicate    = errors.New("já existe uma categoria com este nome")
	ErrCategoriaCorInvalida      = errors.New("cor inválida (formato esperado: #RRGGBB)")
	ErrCategoriaNotFound         = errors.New("categoria não encontrada")
	ErrCategoriaHasServices      = errors.New("não é possível excluir categoria com serviços vinculados")
	ErrCategoriaDescricaoTooLong = errors.New("descrição deve ter no máximo 500 caracteres")

	// Erros de Serviço
	ErrServicoNomeRequired      = errors.New("nome do serviço é obrigatório")
	ErrServicoNomeTooShort      = errors.New("nome do serviço deve ter pelo menos 2 caracteres")
	ErrServicoNomeTooLong       = errors.New("nome do serviço deve ter no máximo 255 caracteres")
	ErrServicoNomeDuplicate     = errors.New("já existe um serviço com este nome")
	ErrServicoPrecoInvalido     = errors.New("preço do serviço deve ser maior que zero")
	ErrServicoDuracaoInvalida   = errors.New("duração do serviço deve ser de pelo menos 5 minutos")
	ErrServicoComissaoInvalida  = errors.New("comissão deve estar entre 0 e 100")
	ErrServicoCorInvalida       = errors.New("cor inválida (formato esperado: #RRGGBB)")
	ErrServicoNotFound          = errors.New("serviço não encontrado")
	ErrServicoInativo           = errors.New("serviço está inativo")
	ErrServicoCategoriaInvalida = errors.New("categoria inválida")

	// Erros de Planos de Assinatura
	ErrPlanNameRequired           = errors.New("nome do plano é obrigatório")
	ErrPlanNameTooShort           = errors.New("nome do plano deve ter pelo menos 3 caracteres")
	ErrPlanNameTooLong            = errors.New("nome do plano deve ter no máximo 100 caracteres")
	ErrPlanValueInvalid           = errors.New("valor do plano deve ser maior que zero")
	ErrPlanInactive               = errors.New("plano inativo")
	ErrPlanNotFound               = errors.New("plano não encontrado")
	ErrPlanNameDuplicate          = errors.New("já existe um plano com este nome")
	ErrPlanHasActiveSubscriptions = errors.New("não é possível desativar plano com assinaturas ativas")

	// Erros de Assinaturas
	ErrSubscriptionNotFound             = errors.New("assinatura não encontrada")
	ErrSubscriptionDuplicateActive      = errors.New("cliente já possui assinatura ativa deste plano")
	ErrSubscriptionInvalidStatus        = errors.New("status de assinatura inválido para esta operação")
	ErrSubscriptionCannotReactivate     = errors.New("assinatura cancelada não pode ser reativada")
	ErrSubscriptionAlreadyCanceled      = errors.New("assinatura já está cancelada")
	ErrSubscriptionPaymentMethodInvalid = errors.New("forma de pagamento inválida")

	// Erros de Despesa Fixa
	ErrDescricaoRequired     = errors.New("descrição é obrigatória")
	ErrDiaVencimentoInvalido = errors.New("dia de vencimento inválido (deve ser entre 1 e 31)")
	ErrDespesaInativa        = errors.New("despesa fixa está inativa")
	ErrDespesaFixaNotFound   = errors.New("despesa fixa não encontrada")
	ErrDespesaFixaJaExiste   = errors.New("já existe despesa fixa com esta descrição")

	// Erros de Caixa Diário
	ErrCaixaNotFound                 = errors.New("caixa diário não encontrado")
	ErrCaixaJaAberto                 = errors.New("já existe um caixa aberto para este tenant")
	ErrCaixaJaFechado                = errors.New("caixa já está fechado")
	ErrCaixaNaoAberto                = errors.New("não há caixa aberto")
	ErrCaixaSaldoInicialNegativo     = errors.New("saldo inicial não pode ser negativo")
	ErrCaixaSaldoRealObrigatorio     = errors.New("saldo real é obrigatório para fechamento")
	ErrCaixaJustificativaObrigatoria = errors.New("justificativa obrigatória para divergência maior que R$ 5,00")
	ErrCaixaOperacaoNaoPermitida     = errors.New("operação não permitida em caixa fechado")

	// Erros de Operações de Caixa
	ErrOperacaoValorInvalido        = errors.New("valor da operação deve ser positivo")
	ErrOperacaoDescricaoObrigatoria = errors.New("descrição é obrigatória")
	ErrOperacaoDescricaoMuitoCurta  = errors.New("descrição deve ter pelo menos 5 caracteres")
	ErrSangriaDestinoObrigatorio    = errors.New("destino é obrigatório para sangria")
	ErrSangriaDestinoInvalido       = errors.New("destino inválido (DEPOSITO, PAGAMENTO, COFRE, OUTROS)")
	ErrSangriaLimiteExcedido        = errors.New("sangria excede o limite permitido para seu perfil")
	ErrReforcoOrigemObrigatoria     = errors.New("origem é obrigatória para reforço")
	ErrReforcoOrigemInvalida        = errors.New("origem inválida (TROCO, CAPITAL_GIRO, TRANSFERENCIA, OUTROS)")

	// Erros de Comissão
	ErrCommissionRuleNameRequired     = errors.New("nome da regra de comissão é obrigatório")
	ErrCommissionRuleNameTooShort     = errors.New("nome da regra deve ter pelo menos 3 caracteres")
	ErrCommissionRulePriorityInvalid  = errors.New("prioridade da regra deve ser maior que zero")
	ErrCommissionRuleInvalidType      = errors.New("tipo de regra de comissão inválido")
	ErrCommissionRuleNotFound         = errors.New("regra de comissão não encontrada")
	ErrCommissionRuleInactive         = errors.New("regra de comissão está inativa")
	ErrCommissionRuleDuplicate        = errors.New("já existe regra de comissão com este nome")
	ErrCommissionRuleTiersRequired    = errors.New("tiers são obrigatórios para regra progressiva")
	ErrCommissionRulePercentRequired  = errors.New("percentual é obrigatório para regras PERCENTAGE ou HYBRID")
	ErrCommissionRuleFixedRequired    = errors.New("valor fixo é obrigatório para regras FIXED ou HYBRID")
	ErrCommissionPeriodNotFound       = errors.New("período de comissão não encontrado")
	ErrCommissionPeriodStartRequired  = errors.New("data de início do período é obrigatória")
	ErrCommissionPeriodEndRequired    = errors.New("data de fim do período é obrigatória")
	ErrCommissionPeriodInvalidRange   = errors.New("data de fim deve ser posterior à data de início")
	ErrCommissionPeriodClosed         = errors.New("período de comissão já está fechado")
	ErrCommissionPeriodPaid           = errors.New("período de comissão já foi pago")
	ErrCommissionPeriodInvalidStatus  = errors.New("status do período de comissão inválido para esta operação")
	ErrCommissionPeriodOverlap        = errors.New("período de comissão se sobrepõe a outro existente")
	ErrAdvanceNotFound                = errors.New("adiantamento não encontrado")
	ErrAdvanceAmountRequired          = errors.New("valor do adiantamento é obrigatório")
	ErrAdvanceAmountInvalid           = errors.New("valor do adiantamento deve ser maior que zero")
	ErrAdvanceProfessionalRequired    = errors.New("profissional é obrigatório para adiantamento")
	ErrAdvanceAlreadyApproved         = errors.New("adiantamento já foi aprovado")
	ErrAdvanceAlreadyRejected         = errors.New("adiantamento já foi rejeitado")
	ErrAdvanceAlreadyDeducted         = errors.New("adiantamento já foi deduzido")
	ErrAdvanceAlreadyCanceled         = errors.New("adiantamento já foi cancelado")
	ErrAdvanceInvalidStatus           = errors.New("status do adiantamento inválido para esta operação")
	ErrAdvanceExceedsAvailable        = errors.New("adiantamento excede o valor disponível de comissão")
	ErrCommissionItemNotFound         = errors.New("item de comissão não encontrado")
	ErrCommissionItemAlreadyProcessed = errors.New("item de comissão já foi processado")
	ErrCommissionItemInvalidAmount    = errors.New("valor da comissão inválido")
	ErrCommissionItemServiceRequired  = errors.New("serviço ou item de comanda é obrigatório")

	// Erros auxiliares de comissão (usados nas entidades)
	ErrMesAnoObrigatorio           = errors.New("mês/ano de referência é obrigatório")
	ErrProfissionalObrigatorio     = errors.New("profissional é obrigatório")
	ErrDataFimAntesInicio          = errors.New("data de fim deve ser posterior à data de início")
	ErrPeriodoNaoPodeFechado       = errors.New("período não pode ser fechado neste status")
	ErrPeriodoNaoPodePago          = errors.New("período não pode ser pago neste status")
	ErrPeriodoPagoNaoCancelavel    = errors.New("período pago não pode ser cancelado")
	ErrAdiantamentoPendente        = errors.New("adiantamento está pendente de aprovação")
	ErrAdiantamentoNaoAprovado     = errors.New("adiantamento não está aprovado")
	ErrValorObrigatorio            = errors.New("valor é obrigatório")
	ErrValorBaseObrigatorio        = errors.New("valor base é obrigatório")
	ErrServicoOuItemObrigatorio    = errors.New("serviço ou item de comanda é obrigatório")
	ErrItemJaProcessado            = errors.New("item já foi processado")
	ErrValorDeveSerPositivo        = errors.New("valor deve ser positivo")
	ErrAdiantamentoNaoPodeAprovar  = errors.New("adiantamento não pode ser aprovado neste status")
	ErrAdiantamentoNaoPodeRejeitar = errors.New("adiantamento não pode ser rejeitado neste status")
	ErrMotivoRejeicaoObrigatorio   = errors.New("motivo da rejeição é obrigatório")
	ErrAdiantamentoNaoPodeDeduzir  = errors.New("adiantamento não pode ser deduzido neste status")
	ErrAdiantamentoNaoPodeCancelar = errors.New("adiantamento não pode ser cancelado neste status")
	ErrTipoComissaoInvalido        = errors.New("tipo de comissão inválido")
	ErrFonteComissaoInvalida       = errors.New("fonte de comissão inválida")
	ErrItemNaoPodeProcessar        = errors.New("item não pode ser processado neste status")
	ErrItemNaoPodePagar            = errors.New("item não pode ser pago neste status")
	ErrItemNaoPodeCancelar         = errors.New("item não pode ser cancelado neste status")
	ErrItemNaoPodeEstornar         = errors.New("item não pode ser estornado neste status")
	ErrNomeObrigatorio             = errors.New("nome é obrigatório")
	ErrPercentualInvalido          = errors.New("percentual inválido (deve estar entre 0 e 100)")
	ErrMaxMenorQueMin              = errors.New("valor máximo deve ser maior que valor mínimo")
)
