// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkCreateUserUnits implements pgx.CopyFromSource.
type iteratorForBulkCreateUserUnits struct {
	rows                 []BulkCreateUserUnitsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateUserUnits) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateUserUnits) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].UnitID,
		r.rows[0].IsDefault,
		r.rows[0].RoleOverride,
	}, nil
}

func (r iteratorForBulkCreateUserUnits) Err() error {
	return nil
}

func (q *Queries) BulkCreateUserUnits(ctx context.Context, arg []BulkCreateUserUnitsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"user_units"}, []string{"user_id", "unit_id", "is_default", "role_override"}, &iteratorForBulkCreateUserUnits{rows: arg})
}
