// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Appointment struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	ProfessionalID        pgtype.UUID        `json:"professional_id"`
	CustomerID            pgtype.UUID        `json:"customer_id"`
	StartTime             pgtype.Timestamptz `json:"start_time"`
	EndTime               pgtype.Timestamptz `json:"end_time"`
	Status                string             `json:"status"`
	TotalPrice            decimal.Decimal    `json:"total_price"`
	Notes                 *string            `json:"notes"`
	CanceledReason        *string            `json:"canceled_reason"`
	GoogleCalendarEventID *string            `json:"google_calendar_event_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type AppointmentService struct {
	AppointmentID     pgtype.UUID        `json:"appointment_id"`
	ServiceID         pgtype.UUID        `json:"service_id"`
	PriceAtBooking    decimal.Decimal    `json:"price_at_booking"`
	DurationAtBooking int32              `json:"duration_at_booking"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Categoria struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Nome      string             `json:"nome"`
	Tipo      string             `json:"tipo"`
	Cor       *string            `json:"cor"`
	Ativa     *bool              `json:"ativa"`
	CriadoEm  pgtype.Timestamptz `json:"criado_em"`
	TipoCusto *string            `json:"tipo_custo"`
}

type Cliente struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	Nome                string             `json:"nome"`
	Email               *string            `json:"email"`
	Telefone            string             `json:"telefone"`
	Cpf                 *string            `json:"cpf"`
	DataNascimento      pgtype.Date        `json:"data_nascimento"`
	Genero              *string            `json:"genero"`
	EnderecoLogradouro  *string            `json:"endereco_logradouro"`
	EnderecoNumero      *string            `json:"endereco_numero"`
	EnderecoComplemento *string            `json:"endereco_complemento"`
	EnderecoBairro      *string            `json:"endereco_bairro"`
	EnderecoCidade      *string            `json:"endereco_cidade"`
	EnderecoEstado      *string            `json:"endereco_estado"`
	EnderecoCep         *string            `json:"endereco_cep"`
	Observacoes         *string            `json:"observacoes"`
	Tags                []string           `json:"tags"`
	Ativo               *bool              `json:"ativo"`
	CriadoEm            pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm        pgtype.Timestamptz `json:"atualizado_em"`
}

// Compensações bancárias com D+ para fluxo de caixa compensado
type CompensacoesBancaria struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	ReceitaID       pgtype.UUID        `json:"receita_id"`
	DataTransacao   pgtype.Date        `json:"data_transacao"`
	DataCompensacao pgtype.Date        `json:"data_compensacao"`
	DataCompensado  pgtype.Date        `json:"data_compensado"`
	ValorBruto      decimal.Decimal    `json:"valor_bruto"`
	TaxaPercentual  pgtype.Numeric     `json:"taxa_percentual"`
	TaxaFixa        pgtype.Numeric     `json:"taxa_fixa"`
	ValorLiquido    decimal.Decimal    `json:"valor_liquido"`
	MeioPagamentoID pgtype.UUID        `json:"meio_pagamento_id"`
	DMais           int32              `json:"d_mais"`
	Status          *string            `json:"status"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm    pgtype.Timestamptz `json:"atualizado_em"`
}

// Contas a pagar com suporte a recorrência e notificações
type ContasAPagar struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Descricao      string             `json:"descricao"`
	CategoriaID    pgtype.UUID        `json:"categoria_id"`
	Fornecedor     *string            `json:"fornecedor"`
	Valor          decimal.Decimal    `json:"valor"`
	Tipo           *string            `json:"tipo"`
	Recorrente     *bool              `json:"recorrente"`
	Periodicidade  *string            `json:"periodicidade"`
	DataVencimento pgtype.Date        `json:"data_vencimento"`
	DataPagamento  pgtype.Date        `json:"data_pagamento"`
	Status         *string            `json:"status"`
	ComprovanteUrl *string            `json:"comprovante_url"`
	PixCode        *string            `json:"pix_code"`
	Observacoes    *string            `json:"observacoes"`
	CriadoEm       pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm   pgtype.Timestamptz `json:"atualizado_em"`
}

// Contas a receber de assinaturas e serviços com alertas de inadimplência
type ContasAReceber struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Origem          *string            `json:"origem"`
	AssinaturaID    pgtype.UUID        `json:"assinatura_id"`
	ServicoID       pgtype.UUID        `json:"servico_id"`
	Descricao       string             `json:"descricao"`
	Valor           decimal.Decimal    `json:"valor"`
	ValorPago       pgtype.Numeric     `json:"valor_pago"`
	DataVencimento  pgtype.Date        `json:"data_vencimento"`
	DataRecebimento pgtype.Date        `json:"data_recebimento"`
	Status          *string            `json:"status"`
	Observacoes     *string            `json:"observacoes"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm    pgtype.Timestamptz `json:"atualizado_em"`
}

// Demonstrativo de Resultado do Exercício mensal por tenant
type DreMensal struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	MesAno               string             `json:"mes_ano"`
	ReceitaServicos      pgtype.Numeric     `json:"receita_servicos"`
	ReceitaProdutos      pgtype.Numeric     `json:"receita_produtos"`
	ReceitaPlanos        pgtype.Numeric     `json:"receita_planos"`
	ReceitaTotal         pgtype.Numeric     `json:"receita_total"`
	CustoComissoes       pgtype.Numeric     `json:"custo_comissoes"`
	CustoInsumos         pgtype.Numeric     `json:"custo_insumos"`
	CustoVariavelTotal   pgtype.Numeric     `json:"custo_variavel_total"`
	DespesaFixa          pgtype.Numeric     `json:"despesa_fixa"`
	DespesaVariavel      pgtype.Numeric     `json:"despesa_variavel"`
	DespesaTotal         pgtype.Numeric     `json:"despesa_total"`
	ResultadoBruto       pgtype.Numeric     `json:"resultado_bruto"`
	ResultadoOperacional pgtype.Numeric     `json:"resultado_operacional"`
	MargemBruta          pgtype.Numeric     `json:"margem_bruta"`
	MargemOperacional    pgtype.Numeric     `json:"margem_operacional"`
	LucroLiquido         pgtype.Numeric     `json:"lucro_liquido"`
	ProcessadoEm         pgtype.Timestamptz `json:"processado_em"`
	CriadoEm             pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm         pgtype.Timestamptz `json:"atualizado_em"`
}

// Fluxo de caixa diário com previsões e compensações bancárias
type FluxoCaixaDiario struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	Data                pgtype.Date        `json:"data"`
	SaldoInicial        pgtype.Numeric     `json:"saldo_inicial"`
	SaldoFinal          pgtype.Numeric     `json:"saldo_final"`
	EntradasConfirmadas pgtype.Numeric     `json:"entradas_confirmadas"`
	EntradasPrevistas   pgtype.Numeric     `json:"entradas_previstas"`
	SaidasPagas         pgtype.Numeric     `json:"saidas_pagas"`
	SaidasPrevistas     pgtype.Numeric     `json:"saidas_previstas"`
	ProcessadoEm        pgtype.Timestamptz `json:"processado_em"`
	CriadoEm            pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm        pgtype.Timestamptz `json:"atualizado_em"`
}

type Fornecedore struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	RazaoSocial         string             `json:"razao_social"`
	NomeFantasia        *string            `json:"nome_fantasia"`
	Cnpj                string             `json:"cnpj"`
	Email               *string            `json:"email"`
	Telefone            *string            `json:"telefone"`
	Celular             *string            `json:"celular"`
	EnderecoLogradouro  *string            `json:"endereco_logradouro"`
	EnderecoNumero      *string            `json:"endereco_numero"`
	EnderecoComplemento *string            `json:"endereco_complemento"`
	EnderecoBairro      *string            `json:"endereco_bairro"`
	EnderecoCidade      *string            `json:"endereco_cidade"`
	EnderecoEstado      *string            `json:"endereco_estado"`
	EnderecoCep         *string            `json:"endereco_cep"`
	Banco               *string            `json:"banco"`
	Agencia             *string            `json:"agencia"`
	Conta               *string            `json:"conta"`
	Observacoes         *string            `json:"observacoes"`
	Ativo               bool               `json:"ativo"`
	CriadoEm            pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm        pgtype.Timestamptz `json:"atualizado_em"`
}

// Metas individuais por barbeiro (serviços gerais, extras, produtos)
type MetasBarbeiro struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	BarbeiroID         pgtype.UUID        `json:"barbeiro_id"`
	MesAno             string             `json:"mes_ano"`
	MetaServicosGerais pgtype.Numeric     `json:"meta_servicos_gerais"`
	MetaServicosExtras pgtype.Numeric     `json:"meta_servicos_extras"`
	MetaProdutos       pgtype.Numeric     `json:"meta_produtos"`
	CriadoEm           pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm       pgtype.Timestamptz `json:"atualizado_em"`
}

// Metas de faturamento mensal por tenant
type MetasMensai struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	MesAno          string             `json:"mes_ano"`
	MetaFaturamento decimal.Decimal    `json:"meta_faturamento"`
	Origem          *string            `json:"origem"`
	Status          *string            `json:"status"`
	CriadoPor       pgtype.UUID        `json:"criado_por"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm    pgtype.Timestamptz `json:"atualizado_em"`
}

// Metas de ticket médio (geral ou por barbeiro)
type MetasTicketMedio struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	MesAno       string             `json:"mes_ano"`
	MetaValor    decimal.Decimal    `json:"meta_valor"`
	Tipo         *string            `json:"tipo"`
	BarbeiroID   pgtype.UUID        `json:"barbeiro_id"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
}

type MovimentacoesEstoque struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	ProdutoID        pgtype.UUID        `json:"produto_id"`
	TipoMovimentacao string             `json:"tipo_movimentacao"`
	Quantidade       decimal.Decimal    `json:"quantidade"`
	ValorUnitario    decimal.Decimal    `json:"valor_unitario"`
	ValorTotal       decimal.Decimal    `json:"valor_total"`
	FornecedorID     pgtype.UUID        `json:"fornecedor_id"`
	UsuarioID        pgtype.UUID        `json:"usuario_id"`
	DataMovimentacao pgtype.Timestamptz `json:"data_movimentacao"`
	Observacoes      *string            `json:"observacoes"`
	Documento        *string            `json:"documento"`
	CriadoEm         pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm     pgtype.Timestamptz `json:"atualizado_em"`
}

// Configurações de precificação padrão por tenant (margem, markup, impostos, comissões)
type PrecificacaoConfig struct {
	ID                        pgtype.UUID        `json:"id"`
	TenantID                  pgtype.UUID        `json:"tenant_id"`
	MargemDesejada            pgtype.Numeric     `json:"margem_desejada"`
	MarkupAlvo                pgtype.Numeric     `json:"markup_alvo"`
	ImpostoPercentual         pgtype.Numeric     `json:"imposto_percentual"`
	ComissaoPercentualDefault pgtype.Numeric     `json:"comissao_percentual_default"`
	CriadoEm                  pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm              pgtype.Timestamptz `json:"atualizado_em"`
}

// Histórico de simulações de precificação com parâmetros e resultados
type PrecificacaoSimulaco struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	ItemID              pgtype.UUID        `json:"item_id"`
	TipoItem            *string            `json:"tipo_item"`
	CustoMateriais      pgtype.Numeric     `json:"custo_materiais"`
	CustoMaoDeObra      pgtype.Numeric     `json:"custo_mao_de_obra"`
	CustoTotal          pgtype.Numeric     `json:"custo_total"`
	MargemDesejada      decimal.Decimal    `json:"margem_desejada"`
	ComissaoPercentual  decimal.Decimal    `json:"comissao_percentual"`
	ImpostoPercentual   decimal.Decimal    `json:"imposto_percentual"`
	PrecoSugerido       decimal.Decimal    `json:"preco_sugerido"`
	PrecoAtual          pgtype.Numeric     `json:"preco_atual"`
	DiferencaPercentual pgtype.Numeric     `json:"diferenca_percentual"`
	LucroEstimado       pgtype.Numeric     `json:"lucro_estimado"`
	MargemFinal         pgtype.Numeric     `json:"margem_final"`
	CustoInsumos        pgtype.Numeric     `json:"custo_insumos"`
	MarkupAplicado      pgtype.Numeric     `json:"markup_aplicado"`
	MargemResultante    pgtype.Numeric     `json:"margem_resultante"`
	ParametrosJson      []byte             `json:"parametros_json"`
	CriadoPor           pgtype.UUID        `json:"criado_por"`
	CriadoEm            pgtype.Timestamptz `json:"criado_em"`
}

type Produto struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	CategoriaID      pgtype.UUID        `json:"categoria_id"`
	Nome             string             `json:"nome"`
	Descricao        *string            `json:"descricao"`
	Sku              *string            `json:"sku"`
	CodigoBarras     *string            `json:"codigo_barras"`
	Preco            decimal.Decimal    `json:"preco"`
	Custo            pgtype.Numeric     `json:"custo"`
	Estoque          *int32             `json:"estoque"`
	EstoqueMinimo    *int32             `json:"estoque_minimo"`
	Unidade          *string            `json:"unidade"`
	Fornecedor       *string            `json:"fornecedor"`
	CategoriaProduto string             `json:"categoria_produto"`
	UnidadeMedida    string             `json:"unidade_medida"`
	QuantidadeAtual  decimal.Decimal    `json:"quantidade_atual"`
	QuantidadeMinima decimal.Decimal    `json:"quantidade_minima"`
	Localizacao      *string            `json:"localizacao"`
	Lote             *string            `json:"lote"`
	DataValidade     pgtype.Date        `json:"data_validade"`
	Ncm              *string            `json:"ncm"`
	PermiteVenda     bool               `json:"permite_venda"`
	Imagem           *string            `json:"imagem"`
	Observacoes      *string            `json:"observacoes"`
	Ativo            *bool              `json:"ativo"`
	CriadoEm         pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm     pgtype.Timestamptz `json:"atualizado_em"`
}

type ProdutoFornecedor struct {
	ID                     pgtype.UUID        `json:"id"`
	TenantID               pgtype.UUID        `json:"tenant_id"`
	ProdutoID              pgtype.UUID        `json:"produto_id"`
	FornecedorID           pgtype.UUID        `json:"fornecedor_id"`
	CodigoFornecedor       *string            `json:"codigo_fornecedor"`
	PrecoCompra            pgtype.Numeric     `json:"preco_compra"`
	PrazoEntregaDias       *int32             `json:"prazo_entrega_dias"`
	FornecedorPreferencial *bool              `json:"fornecedor_preferencial"`
	Ativo                  bool               `json:"ativo"`
	CriadoEm               pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm           pgtype.Timestamptz `json:"atualizado_em"`
}

type Profissionai struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Nome            string             `json:"nome"`
	Email           string             `json:"email"`
	Telefone        string             `json:"telefone"`
	Cpf             string             `json:"cpf"`
	Especialidades  []string           `json:"especialidades"`
	Comissao        pgtype.Numeric     `json:"comissao"`
	TipoComissao    *string            `json:"tipo_comissao"`
	Foto            *string            `json:"foto"`
	DataAdmissao    pgtype.Date        `json:"data_admissao"`
	DataDemissao    pgtype.Date        `json:"data_demissao"`
	Status          *string            `json:"status"`
	HorarioTrabalho []byte             `json:"horario_trabalho"`
	Observacoes     *string            `json:"observacoes"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm    pgtype.Timestamptz `json:"atualizado_em"`
	Tipo            string             `json:"tipo"`
	Cor             *string            `json:"cor"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Servico struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	CategoriaID      pgtype.UUID        `json:"categoria_id"`
	Nome             string             `json:"nome"`
	Descricao        *string            `json:"descricao"`
	Preco            decimal.Decimal    `json:"preco"`
	Duracao          int32              `json:"duracao"`
	Comissao         pgtype.Numeric     `json:"comissao"`
	Cor              *string            `json:"cor"`
	Imagem           *string            `json:"imagem"`
	ProfissionaisIds []pgtype.UUID      `json:"profissionais_ids"`
	Observacoes      *string            `json:"observacoes"`
	Tags             []string           `json:"tags"`
	Ativo            *bool              `json:"ativo"`
	CriadoEm         pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm     pgtype.Timestamptz `json:"atualizado_em"`
}

type Tenant struct {
	ID                  pgtype.UUID        `json:"id"`
	Nome                string             `json:"nome"`
	Cnpj                *string            `json:"cnpj"`
	Ativo               *bool              `json:"ativo"`
	Plano               *string            `json:"plano"`
	CriadoEm            pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm        pgtype.Timestamptz `json:"atualizado_em"`
	OnboardingCompleted *bool              `json:"onboarding_completed"`
	OnboardingStep      *int32             `json:"onboarding_step"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Nome         string             `json:"nome"`
	Role         string             `json:"role"`
	Ativo        *bool              `json:"ativo"`
	UltimoLogin  pgtype.Timestamptz `json:"ultimo_login"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type UserPreference struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	AnalyticsEnabled     bool               `json:"analytics_enabled"`
	ErrorTrackingEnabled bool               `json:"error_tracking_enabled"`
	MarketingEnabled     bool               `json:"marketing_enabled"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
