// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ============================================================================
	// BARBER TURN QUERIES (sqlc)
	// Módulo Lista da Vez — NEXO v1.0
	// Conforme FLUXO_LISTA_DA_VEZ.md
	// ============================================================================
	// ============================================================================
	// CREATE / ADD
	// ============================================================================
	// Adiciona um barbeiro à lista da vez
	AddBarberToTurnList(ctx context.Context, arg AddBarberToTurnListParams) (BarbersTurnList, error)
	AprovarMetaMensal(ctx context.Context, arg AprovarMetaMensalParams) (MetasMensai, error)
	AtualizarQuantidadeProduto(ctx context.Context, arg AtualizarQuantidadeProdutoParams) (Produto, error)
	AvgMargemBrutaByPeriod(ctx context.Context, arg AvgMargemBrutaByPeriodParams) (interface{}, error)
	AvgMargemOperacionalByPeriod(ctx context.Context, arg AvgMargemOperacionalByPeriodParams) (interface{}, error)
	CheckAppointmentConflict(ctx context.Context, arg CheckAppointmentConflictParams) (bool, error)
	CheckCPFExists(ctx context.Context, arg CheckCPFExistsParams) (bool, error)
	CheckCategoriaServicoNomeExists(ctx context.Context, arg CheckCategoriaServicoNomeExistsParams) (bool, error)
	CheckCpfExistsProfessional(ctx context.Context, arg CheckCpfExistsProfessionalParams) (bool, error)
	CheckEmailExists(ctx context.Context, arg CheckEmailExistsParams) (bool, error)
	CheckEmailExistsProfessional(ctx context.Context, arg CheckEmailExistsProfessionalParams) (bool, error)
	// ============================================================================
	// VALIDAÇÕES
	// ============================================================================
	CheckPhoneExists(ctx context.Context, arg CheckPhoneExistsParams) (bool, error)
	// ============================================================================
	// VALIDAÇÕES
	// ============================================================================
	// Verifica se profissional já está na lista
	CheckProfessionalInTurnList(ctx context.Context, arg CheckProfessionalInTurnListParams) (bool, error)
	// Verifica se profissional é do tipo BARBEIRO
	CheckProfessionalIsBarber(ctx context.Context, arg CheckProfessionalIsBarberParams) (bool, error)
	CountAppointments(ctx context.Context, arg CountAppointmentsParams) (int64, error)
	CountAppointmentsByStatus(ctx context.Context, arg CountAppointmentsByStatusParams) (int64, error)
	CountBarbersTurnList(ctx context.Context, tenantID pgtype.UUID) (CountBarbersTurnListRow, error)
	CountCategoriasServicosByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountCompensacoesByStatus(ctx context.Context, arg CountCompensacoesByStatusParams) (int64, error)
	CountCompensacoesByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountContasPagarByStatus(ctx context.Context, arg CountContasPagarByStatusParams) (int64, error)
	CountContasPagarByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountContasReceberByStatus(ctx context.Context, arg CountContasReceberByStatusParams) (int64, error)
	CountContasReceberByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error)
	CountDREMensalByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountFluxoCaixaDiarioByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountMetasBarbeiroByBarbeiro(ctx context.Context, arg CountMetasBarbeiroByBarbeiroParams) (int64, error)
	CountMetasBarbeiroByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountMetasMensaisByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountMetasTicketMedioByBarbeiro(ctx context.Context, arg CountMetasTicketMedioByBarbeiroParams) (int64, error)
	CountMetasTicketMedioByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountProfessionals(ctx context.Context, arg CountProfessionalsParams) (int64, error)
	// ============================================================================
	// QUERIES AUXILIARES
	// ============================================================================
	CountServicosInCategoria(ctx context.Context, arg CountServicosInCategoriaParams) (int64, error)
	CountSimulacoesByItem(ctx context.Context, arg CountSimulacoesByItemParams) (int64, error)
	CountSimulacoesByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountUserPreferences(ctx context.Context) (int64, error)
	// ============================================================================
	// APPOINTMENTS QUERIES (sqlc)
	// Módulo de Agendamento — NEXO v1.0
	// ============================================================================
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	CreateAppointmentService(ctx context.Context, arg CreateAppointmentServiceParams) error
	// ============================================================================
	// CATEGORIAS DE SERVIÇOS QUERIES (sqlc)
	// Módulo de Cadastro de Serviços — NEXO v1.0
	// Tabela: categorias_servicos (separada de categorias financeiras)
	// ============================================================================
	// ============================================================================
	// CREATE
	// ============================================================================
	CreateCategoriaServico(ctx context.Context, arg CreateCategoriaServicoParams) (CategoriasServico, error)
	CreateCompensacaoBancaria(ctx context.Context, arg CreateCompensacaoBancariaParams) (CompensacoesBancaria, error)
	CreateContaPagar(ctx context.Context, arg CreateContaPagarParams) (ContasAPagar, error)
	CreateContaReceber(ctx context.Context, arg CreateContaReceberParams) (ContasAReceber, error)
	// ============================================================================
	// CUSTOMERS QUERIES (sqlc)
	// Módulo de Cadastro de Clientes — NEXO v1.0
	// Conforme FLUXO_CADASTROS_CLIENTE.md
	// ============================================================================
	// ============================================================================
	// CREATE
	// ============================================================================
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Cliente, error)
	CreateDREMensal(ctx context.Context, arg CreateDREMensalParams) (DreMensal, error)
	CreateFluxoCaixaDiario(ctx context.Context, arg CreateFluxoCaixaDiarioParams) (FluxoCaixaDiario, error)
	// ========================================
	// QUERIES SQL - MÓDULO DE ESTOQUE
	// Geradas via sqlc para type-safety
	// ========================================
	// ========================================
	// FORNECEDORES
	// ========================================
	CreateFornecedor(ctx context.Context, arg CreateFornecedorParams) (Fornecedore, error)
	CreateMetaBarbeiro(ctx context.Context, arg CreateMetaBarbeiroParams) (MetasBarbeiro, error)
	CreateMetaMensal(ctx context.Context, arg CreateMetaMensalParams) (MetasMensai, error)
	CreateMetaTicketMedio(ctx context.Context, arg CreateMetaTicketMedioParams) (MetasTicketMedio, error)
	// ========================================
	// MOVIMENTAÇÕES DE ESTOQUE
	// ========================================
	CreateMovimentacaoEstoque(ctx context.Context, arg CreateMovimentacaoEstoqueParams) (MovimentacoesEstoque, error)
	CreatePrecificacaoConfig(ctx context.Context, arg CreatePrecificacaoConfigParams) (PrecificacaoConfig, error)
	CreatePrecificacaoSimulacao(ctx context.Context, arg CreatePrecificacaoSimulacaoParams) (PrecificacaoSimulaco, error)
	// ========================================
	// PRODUTOS (operações de estoque)
	// ========================================
	CreateProduto(ctx context.Context, arg CreateProdutoParams) (Produto, error)
	// ========================================
	// PRODUTO-FORNECEDOR (relacionamento)
	// ========================================
	CreateProdutoFornecedor(ctx context.Context, arg CreateProdutoFornecedorParams) (ProdutoFornecedor, error)
	CreateProfessional(ctx context.Context, arg CreateProfessionalParams) (CreateProfessionalRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) (UserPreference, error)
	CustomerExists(ctx context.Context, arg CustomerExistsParams) (bool, error)
	DeleteAppointment(ctx context.Context, arg DeleteAppointmentParams) error
	DeleteAppointmentServices(ctx context.Context, appointmentID pgtype.UUID) error
	// ============================================================================
	// DELETE
	// ============================================================================
	DeleteCategoriaServico(ctx context.Context, arg DeleteCategoriaServicoParams) error
	DeleteCompensacaoBancaria(ctx context.Context, arg DeleteCompensacaoBancariaParams) error
	DeleteContaPagar(ctx context.Context, arg DeleteContaPagarParams) error
	DeleteContaReceber(ctx context.Context, arg DeleteContaReceberParams) error
	DeleteDREMensal(ctx context.Context, arg DeleteDREMensalParams) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteFluxoCaixaDiario(ctx context.Context, arg DeleteFluxoCaixaDiarioParams) error
	DeleteFornecedor(ctx context.Context, arg DeleteFornecedorParams) error
	DeleteMetaBarbeiro(ctx context.Context, arg DeleteMetaBarbeiroParams) error
	DeleteMetaMensal(ctx context.Context, arg DeleteMetaMensalParams) error
	DeleteMetaTicketMedio(ctx context.Context, arg DeleteMetaTicketMedioParams) error
	DeletePrecificacaoConfig(ctx context.Context, arg DeletePrecificacaoConfigParams) error
	DeletePrecificacaoSimulacao(ctx context.Context, arg DeletePrecificacaoSimulacaoParams) error
	DeleteProduto(ctx context.Context, arg DeleteProdutoParams) error
	DeleteProdutoFornecedor(ctx context.Context, arg DeleteProdutoFornecedorParams) error
	DeleteProfessional(ctx context.Context, arg DeleteProfessionalParams) error
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteUserPreferences(ctx context.Context, userID pgtype.UUID) error
	GetAppointmentByID(ctx context.Context, arg GetAppointmentByIDParams) (GetAppointmentByIDRow, error)
	GetAppointmentServices(ctx context.Context, appointmentID pgtype.UUID) ([]GetAppointmentServicesRow, error)
	// Lista barbeiros ativos que ainda não estão na lista da vez
	GetAvailableBarbersForTurnList(ctx context.Context, tenantID pgtype.UUID) ([]GetAvailableBarbersForTurnListRow, error)
	// ============================================================================
	// READ / LIST
	// ============================================================================
	GetBarberTurnByID(ctx context.Context, arg GetBarberTurnByIDParams) (GetBarberTurnByIDRow, error)
	GetBarberTurnByProfessionalID(ctx context.Context, arg GetBarberTurnByProfessionalIDParams) (GetBarberTurnByProfessionalIDRow, error)
	// ============================================================================
	// READ
	// ============================================================================
	GetCategoriaServicoByID(ctx context.Context, arg GetCategoriaServicoByIDParams) (CategoriasServico, error)
	GetCategoriasServicosComServicos(ctx context.Context, tenantID pgtype.UUID) ([]GetCategoriasServicosComServicosRow, error)
	GetCompensacaoBancariaByID(ctx context.Context, arg GetCompensacaoBancariaByIDParams) (CompensacoesBancaria, error)
	GetContaPagarByID(ctx context.Context, arg GetContaPagarByIDParams) (ContasAPagar, error)
	GetContaReceberByID(ctx context.Context, arg GetContaReceberByIDParams) (ContasAReceber, error)
	GetCurvaABC(ctx context.Context, tenantID pgtype.UUID) ([]GetCurvaABCRow, error)
	GetCustomerByCPF(ctx context.Context, arg GetCustomerByCPFParams) (Cliente, error)
	// ============================================================================
	// READ
	// ============================================================================
	GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Cliente, error)
	GetCustomerByPhone(ctx context.Context, arg GetCustomerByPhoneParams) (Cliente, error)
	// ============================================================================
	// EXPORTAÇÃO LGPD
	// ============================================================================
	GetCustomerDataForExport(ctx context.Context, arg GetCustomerDataForExportParams) (GetCustomerDataForExportRow, error)
	GetCustomerInfo(ctx context.Context, arg GetCustomerInfoParams) (GetCustomerInfoRow, error)
	// ============================================================================
	// ESTATÍSTICAS E RELATÓRIOS
	// ============================================================================
	GetCustomerStats(ctx context.Context, tenantID pgtype.UUID) (GetCustomerStatsRow, error)
	GetCustomerWithHistory(ctx context.Context, arg GetCustomerWithHistoryParams) (GetCustomerWithHistoryRow, error)
	GetDREMensalByID(ctx context.Context, arg GetDREMensalByIDParams) (DreMensal, error)
	GetDREMensalByMesAno(ctx context.Context, arg GetDREMensalByMesAnoParams) (DreMensal, error)
	GetDailyAppointmentStats(ctx context.Context, arg GetDailyAppointmentStatsParams) (GetDailyAppointmentStatsRow, error)
	// Relatório diário: pontos ganhos em uma data específica
	// Nota: Esta query usa CTE para calcular incrementos comparando com o dia anterior
	GetDailyReportByDate(ctx context.Context, arg GetDailyReportByDateParams) ([]GetDailyReportByDateRow, error)
	GetFluxoCaixaDiarioByData(ctx context.Context, arg GetFluxoCaixaDiarioByDataParams) (FluxoCaixaDiario, error)
	GetFluxoCaixaDiarioByID(ctx context.Context, arg GetFluxoCaixaDiarioByIDParams) (FluxoCaixaDiario, error)
	GetFornecedorByCNPJ(ctx context.Context, arg GetFornecedorByCNPJParams) (Fornecedore, error)
	GetFornecedorByID(ctx context.Context, arg GetFornecedorByIDParams) (Fornecedore, error)
	GetMetaBarbeiroByID(ctx context.Context, arg GetMetaBarbeiroByIDParams) (MetasBarbeiro, error)
	GetMetaBarbeiroByMesAno(ctx context.Context, arg GetMetaBarbeiroByMesAnoParams) (MetasBarbeiro, error)
	GetMetaMensalByID(ctx context.Context, arg GetMetaMensalByIDParams) (MetasMensai, error)
	GetMetaMensalByMesAno(ctx context.Context, arg GetMetaMensalByMesAnoParams) (MetasMensai, error)
	GetMetaTicketMedioBarbeiroByMesAno(ctx context.Context, arg GetMetaTicketMedioBarbeiroByMesAnoParams) (MetasTicketMedio, error)
	GetMetaTicketMedioByID(ctx context.Context, arg GetMetaTicketMedioByIDParams) (MetasTicketMedio, error)
	GetMetaTicketMedioGeralByMesAno(ctx context.Context, arg GetMetaTicketMedioGeralByMesAnoParams) (MetasTicketMedio, error)
	GetMovimentacaoByID(ctx context.Context, arg GetMovimentacaoByIDParams) (MovimentacoesEstoque, error)
	GetMovimentacoesPorPeriodoComDetalhes(ctx context.Context, arg GetMovimentacoesPorPeriodoComDetalhesParams) ([]GetMovimentacoesPorPeriodoComDetalhesRow, error)
	// Retorna o próximo barbeiro da vez (topo da fila ativa)
	GetNextBarber(ctx context.Context, tenantID pgtype.UUID) (GetNextBarberRow, error)
	GetPrecificacaoConfigByID(ctx context.Context, arg GetPrecificacaoConfigByIDParams) (PrecificacaoConfig, error)
	GetPrecificacaoConfigByTenant(ctx context.Context, tenantID pgtype.UUID) (PrecificacaoConfig, error)
	GetPrecificacaoSimulacaoByID(ctx context.Context, arg GetPrecificacaoSimulacaoByIDParams) (PrecificacaoSimulaco, error)
	GetProdutoByID(ctx context.Context, arg GetProdutoByIDParams) (Produto, error)
	GetProdutoBySKU(ctx context.Context, arg GetProdutoBySKUParams) (Produto, error)
	GetProdutoFornecedor(ctx context.Context, arg GetProdutoFornecedorParams) (ProdutoFornecedor, error)
	// ========================================
	// RELATÓRIOS E CONSULTAS ESPECIAIS
	// ========================================
	GetProdutosComEstoqueBaixo(ctx context.Context, tenantID pgtype.UUID) ([]GetProdutosComEstoqueBaixoRow, error)
	GetProfessionalByID(ctx context.Context, arg GetProfessionalByIDParams) (GetProfessionalByIDRow, error)
	GetProfessionalInfo(ctx context.Context, arg GetProfessionalInfoParams) (GetProfessionalInfoRow, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetServiceInfo(ctx context.Context, arg GetServiceInfoParams) (GetServiceInfoRow, error)
	GetServicesByIDs(ctx context.Context, arg GetServicesByIDsParams) ([]GetServicesByIDsRow, error)
	// ============================================================================
	// ESTATÍSTICAS DIÁRIAS
	// ============================================================================
	// Estatísticas do dia atual
	GetTodayStats(ctx context.Context, tenantID pgtype.UUID) (GetTodayStatsRow, error)
	GetTotalPorTipo(ctx context.Context, arg GetTotalPorTipoParams) (GetTotalPorTipoRow, error)
	// Busca histórico de um mês específico
	GetTurnHistoryByMonth(ctx context.Context, arg GetTurnHistoryByMonthParams) ([]GetTurnHistoryByMonthRow, error)
	// Resumo dos últimos 12 meses
	GetTurnHistorySummary(ctx context.Context, tenantID pgtype.UUID) ([]GetTurnHistorySummaryRow, error)
	GetUltimaSimulacaoByItem(ctx context.Context, arg GetUltimaSimulacaoByItemParams) (PrecificacaoSimulaco, error)
	GetUltimoSaldo(ctx context.Context, arg GetUltimoSaldoParams) (pgtype.Numeric, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	GetUserPreferencesByID(ctx context.Context, id pgtype.UUID) (UserPreference, error)
	GetUserPreferencesByUserID(ctx context.Context, userID pgtype.UUID) (UserPreference, error)
	GetValorTotalEstoque(ctx context.Context, tenantID pgtype.UUID) (GetValorTotalEstoqueRow, error)
	// ============================================================================
	// DELETE (Soft Delete)
	// ============================================================================
	InactivateCustomer(ctx context.Context, arg InactivateCustomerParams) error
	// Lista apenas barbeiros ativos na fila (is_active = true)
	ListActiveBarbersTurnList(ctx context.Context, tenantID pgtype.UUID) ([]ListActiveBarbersTurnListRow, error)
	ListActiveCustomers(ctx context.Context, tenantID pgtype.UUID) ([]ListActiveCustomersRow, error)
	ListActiveProfessionals(ctx context.Context, tenantID pgtype.UUID) ([]ListActiveProfessionalsRow, error)
	ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]ListAppointmentsRow, error)
	ListAppointmentsByCustomer(ctx context.Context, arg ListAppointmentsByCustomerParams) ([]ListAppointmentsByCustomerRow, error)
	ListAppointmentsByProfessionalAndDateRange(ctx context.Context, arg ListAppointmentsByProfessionalAndDateRangeParams) ([]ListAppointmentsByProfessionalAndDateRangeRow, error)
	ListBarbers(ctx context.Context, tenantID pgtype.UUID) ([]ListBarbersRow, error)
	// Lista todos os barbeiros na fila ordenados por pontuação
	// Menor pontuação = topo da fila
	// Critério de desempate: last_turn_at mais antigo ou nulo (nunca atendeu) → topo
	// Segundo desempate: ordem de criação (created_at ASC)
	ListBarbersTurnList(ctx context.Context, arg ListBarbersTurnListParams) ([]ListBarbersTurnListRow, error)
	ListCategoriasServicos(ctx context.Context, tenantID pgtype.UUID) ([]CategoriasServico, error)
	ListCategoriasServicosAtivas(ctx context.Context, tenantID pgtype.UUID) ([]CategoriasServico, error)
	ListCompensacoesBancariasByTenant(ctx context.Context, arg ListCompensacoesBancariasByTenantParams) ([]CompensacoesBancaria, error)
	ListCompensacoesByDataCompensacao(ctx context.Context, arg ListCompensacoesByDataCompensacaoParams) ([]CompensacoesBancaria, error)
	ListCompensacoesByReceita(ctx context.Context, arg ListCompensacoesByReceitaParams) ([]CompensacoesBancaria, error)
	ListCompensacoesByStatus(ctx context.Context, arg ListCompensacoesByStatusParams) ([]CompensacoesBancaria, error)
	ListContasPagarByPeriod(ctx context.Context, arg ListContasPagarByPeriodParams) ([]ContasAPagar, error)
	ListContasPagarByStatus(ctx context.Context, arg ListContasPagarByStatusParams) ([]ContasAPagar, error)
	ListContasPagarByTenant(ctx context.Context, arg ListContasPagarByTenantParams) ([]ContasAPagar, error)
	ListContasPagarRecorrentes(ctx context.Context, tenantID pgtype.UUID) ([]ContasAPagar, error)
	ListContasPagarVencidas(ctx context.Context, arg ListContasPagarVencidasParams) ([]ContasAPagar, error)
	ListContasReceberByAssinatura(ctx context.Context, arg ListContasReceberByAssinaturaParams) ([]ContasAReceber, error)
	ListContasReceberByOrigem(ctx context.Context, arg ListContasReceberByOrigemParams) ([]ContasAReceber, error)
	ListContasReceberByPeriod(ctx context.Context, arg ListContasReceberByPeriodParams) ([]ContasAReceber, error)
	ListContasReceberByStatus(ctx context.Context, arg ListContasReceberByStatusParams) ([]ContasAReceber, error)
	ListContasReceberByTenant(ctx context.Context, arg ListContasReceberByTenantParams) ([]ContasAReceber, error)
	ListContasReceberVencidas(ctx context.Context, arg ListContasReceberVencidasParams) ([]ContasAReceber, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Cliente, error)
	ListCustomersWithoutAppointments(ctx context.Context, arg ListCustomersWithoutAppointmentsParams) ([]Cliente, error)
	ListDREMensalByPeriod(ctx context.Context, arg ListDREMensalByPeriodParams) ([]DreMensal, error)
	ListDREMensalByTenant(ctx context.Context, arg ListDREMensalByTenantParams) ([]DreMensal, error)
	ListFluxoCaixaDiarioByPeriod(ctx context.Context, arg ListFluxoCaixaDiarioByPeriodParams) ([]FluxoCaixaDiario, error)
	ListFluxoCaixaDiarioByTenant(ctx context.Context, arg ListFluxoCaixaDiarioByTenantParams) ([]FluxoCaixaDiario, error)
	ListFornecedores(ctx context.Context, tenantID pgtype.UUID) ([]Fornecedore, error)
	ListFornecedoresAtivos(ctx context.Context, tenantID pgtype.UUID) ([]Fornecedore, error)
	ListFornecedoresByProduto(ctx context.Context, arg ListFornecedoresByProdutoParams) ([]ListFornecedoresByProdutoRow, error)
	ListMetasBarbeiroByBarbeiro(ctx context.Context, arg ListMetasBarbeiroByBarbeiroParams) ([]MetasBarbeiro, error)
	ListMetasBarbeiroByMesAno(ctx context.Context, arg ListMetasBarbeiroByMesAnoParams) ([]MetasBarbeiro, error)
	ListMetasBarbeiroByTenant(ctx context.Context, arg ListMetasBarbeiroByTenantParams) ([]MetasBarbeiro, error)
	ListMetasMensaisByPeriod(ctx context.Context, arg ListMetasMensaisByPeriodParams) ([]MetasMensai, error)
	ListMetasMensaisByStatus(ctx context.Context, arg ListMetasMensaisByStatusParams) ([]MetasMensai, error)
	ListMetasMensaisByTenant(ctx context.Context, arg ListMetasMensaisByTenantParams) ([]MetasMensai, error)
	ListMetasTicketMedioByBarbeiro(ctx context.Context, arg ListMetasTicketMedioByBarbeiroParams) ([]MetasTicketMedio, error)
	ListMetasTicketMedioByMesAno(ctx context.Context, arg ListMetasTicketMedioByMesAnoParams) ([]MetasTicketMedio, error)
	ListMetasTicketMedioByTenant(ctx context.Context, arg ListMetasTicketMedioByTenantParams) ([]MetasTicketMedio, error)
	ListMovimentacoesByFornecedor(ctx context.Context, arg ListMovimentacoesByFornecedorParams) ([]MovimentacoesEstoque, error)
	ListMovimentacoesByPeriodo(ctx context.Context, arg ListMovimentacoesByPeriodoParams) ([]MovimentacoesEstoque, error)
	ListMovimentacoesByProduto(ctx context.Context, arg ListMovimentacoesByProdutoParams) ([]MovimentacoesEstoque, error)
	ListMovimentacoesByTipo(ctx context.Context, arg ListMovimentacoesByTipoParams) ([]MovimentacoesEstoque, error)
	ListProdutos(ctx context.Context, tenantID pgtype.UUID) ([]Produto, error)
	ListProdutosAbaixoDoMinimo(ctx context.Context, tenantID pgtype.UUID) ([]Produto, error)
	ListProdutosAtivos(ctx context.Context, tenantID pgtype.UUID) ([]Produto, error)
	ListProdutosByCategoria(ctx context.Context, arg ListProdutosByCategoriaParams) ([]Produto, error)
	ListProdutosByFornecedor(ctx context.Context, arg ListProdutosByFornecedorParams) ([]ListProdutosByFornecedorRow, error)
	// =============================================================================
	// QUERIES PARA PROFISSIONAIS
	// =============================================================================
	ListProfessionals(ctx context.Context, arg ListProfessionalsParams) ([]ListProfessionalsRow, error)
	ListSimulacoesByItem(ctx context.Context, arg ListSimulacoesByItemParams) ([]PrecificacaoSimulaco, error)
	ListSimulacoesByTenant(ctx context.Context, arg ListSimulacoesByTenantParams) ([]PrecificacaoSimulaco, error)
	ListSimulacoesByTipoItem(ctx context.Context, arg ListSimulacoesByTipoItemParams) ([]PrecificacaoSimulaco, error)
	ListSimulacoesByUsuario(ctx context.Context, arg ListSimulacoesByUsuarioParams) ([]PrecificacaoSimulaco, error)
	// ============================================================================
	// HISTÓRICO
	// ============================================================================
	// Lista histórico mensal de atendimentos
	ListTurnHistory(ctx context.Context, arg ListTurnHistoryParams) ([]ListTurnHistoryRow, error)
	ListUsersWithAnalyticsEnabled(ctx context.Context) ([]pgtype.UUID, error)
	ListUsersWithMarketingEnabled(ctx context.Context) ([]pgtype.UUID, error)
	MarcarComoCompensado(ctx context.Context, arg MarcarComoCompensadoParams) (CompensacoesBancaria, error)
	MarcarContaPagarComoAtrasada(ctx context.Context, arg MarcarContaPagarComoAtrasadaParams) error
	MarcarContaPagarComoPaga(ctx context.Context, arg MarcarContaPagarComoPagaParams) (ContasAPagar, error)
	MarcarContaReceberComoAtrasada(ctx context.Context, arg MarcarContaReceberComoAtrasadaParams) error
	MarcarContaReceberComoRecebida(ctx context.Context, arg MarcarContaReceberComoRecebidaParams) (ContasAReceber, error)
	// ============================================================================
	// QUERIES AUXILIARES: Profissionais, Clientes, Serviços (Read-Only)
	// ============================================================================
	ProfessionalExists(ctx context.Context, arg ProfessionalExistsParams) (bool, error)
	ReactivateCustomer(ctx context.Context, arg ReactivateCustomerParams) error
	ReativarFornecedor(ctx context.Context, arg ReativarFornecedorParams) error
	// ============================================================================
	// UPDATE
	// ============================================================================
	// Registra um atendimento: incrementa pontos (+1) e atualiza timestamp
	RecordTurn(ctx context.Context, arg RecordTurnParams) (BarbersTurnList, error)
	RejeitarMetaMensal(ctx context.Context, arg RejeitarMetaMensalParams) (MetasMensai, error)
	// ============================================================================
	// DELETE
	// ============================================================================
	// Remove barbeiro da lista da vez
	RemoveBarberFromTurnList(ctx context.Context, arg RemoveBarberFromTurnListParams) error
	// ============================================================================
	// RESET MENSAL
	// ============================================================================
	// Zera todos os pontos e last_turn_at para reset mensal
	ResetAllTurnPoints(ctx context.Context, tenantID pgtype.UUID) error
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error
	// Salva snapshot no histórico antes do reset
	SaveTurnHistoryBeforeReset(ctx context.Context, arg SaveTurnHistoryBeforeResetParams) error
	SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]SearchCustomersRow, error)
	ServiceExists(ctx context.Context, arg ServiceExistsParams) (bool, error)
	// Ativa um barbeiro na fila
	SetBarberTurnActive(ctx context.Context, arg SetBarberTurnActiveParams) (BarbersTurnList, error)
	// Pausa um barbeiro na fila
	SetBarberTurnInactive(ctx context.Context, arg SetBarberTurnInactiveParams) (BarbersTurnList, error)
	SumContasPagarByPeriod(ctx context.Context, arg SumContasPagarByPeriodParams) (interface{}, error)
	SumContasPagasByPeriod(ctx context.Context, arg SumContasPagasByPeriodParams) (interface{}, error)
	SumContasReceberByPeriod(ctx context.Context, arg SumContasReceberByPeriodParams) (interface{}, error)
	SumContasRecebidasByPeriod(ctx context.Context, arg SumContasRecebidasByPeriodParams) (interface{}, error)
	SumDespesasByPeriod(ctx context.Context, arg SumDespesasByPeriodParams) (interface{}, error)
	SumEntradasByPeriod(ctx context.Context, arg SumEntradasByPeriodParams) (interface{}, error)
	SumReceitasByPeriod(ctx context.Context, arg SumReceitasByPeriodParams) (interface{}, error)
	SumSaidasByPeriod(ctx context.Context, arg SumSaidasByPeriodParams) (interface{}, error)
	SumValorLiquidoByPeriod(ctx context.Context, arg SumValorLiquidoByPeriodParams) (interface{}, error)
	// Alterna status ativo/inativo de um barbeiro na fila
	ToggleBarberTurnStatus(ctx context.Context, arg ToggleBarberTurnStatusParams) (BarbersTurnList, error)
	ToggleCategoriaServicoStatus(ctx context.Context, arg ToggleCategoriaServicoStatusParams) (CategoriasServico, error)
	UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error)
	UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (Appointment, error)
	// ============================================================================
	// UPDATE
	// ============================================================================
	UpdateCategoriaServico(ctx context.Context, arg UpdateCategoriaServicoParams) (CategoriasServico, error)
	UpdateCompensacaoBancaria(ctx context.Context, arg UpdateCompensacaoBancariaParams) (CompensacoesBancaria, error)
	UpdateContaPagar(ctx context.Context, arg UpdateContaPagarParams) (ContasAPagar, error)
	UpdateContaReceber(ctx context.Context, arg UpdateContaReceberParams) (ContasAReceber, error)
	// ============================================================================
	// UPDATE
	// ============================================================================
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Cliente, error)
	UpdateCustomerTags(ctx context.Context, arg UpdateCustomerTagsParams) (Cliente, error)
	UpdateDREMensal(ctx context.Context, arg UpdateDREMensalParams) (DreMensal, error)
	UpdateFluxoCaixaDiario(ctx context.Context, arg UpdateFluxoCaixaDiarioParams) (FluxoCaixaDiario, error)
	UpdateFornecedor(ctx context.Context, arg UpdateFornecedorParams) (Fornecedore, error)
	UpdateLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateMetaBarbeiro(ctx context.Context, arg UpdateMetaBarbeiroParams) (MetasBarbeiro, error)
	UpdateMetaMensal(ctx context.Context, arg UpdateMetaMensalParams) (MetasMensai, error)
	UpdateMetaTicketMedio(ctx context.Context, arg UpdateMetaTicketMedioParams) (MetasTicketMedio, error)
	UpdatePrecificacaoConfig(ctx context.Context, arg UpdatePrecificacaoConfigParams) (PrecificacaoConfig, error)
	UpdateProduto(ctx context.Context, arg UpdateProdutoParams) (Produto, error)
	UpdateProdutoFornecedor(ctx context.Context, arg UpdateProdutoFornecedorParams) (ProdutoFornecedor, error)
	UpdateProfessional(ctx context.Context, arg UpdateProfessionalParams) (UpdateProfessionalRow, error)
	UpdateProfessionalStatus(ctx context.Context, arg UpdateProfessionalStatusParams) (UpdateProfessionalStatusRow, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error)
}

var _ Querier = (*Queries)(nil)
